<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
	<VersionPrefix>1.0.0</VersionPrefix>
	  
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <UseWPF>False</UseWPF>
    <ApplicationIcon>Serial.ico</ApplicationIcon>
    <StartupObject></StartupObject>


    <OptimizationPreference>Size</OptimizationPreference>
    <StackTraceSupport>false</StackTraceSupport>
    





	<PathMap>$(MSBuildProjectDirectory)=./</PathMap>
    





	<Authors>Cwrstata</Authors>
    





	<Product>cw-Serial-Monitor</Product>
    





	<PackageReadmeFile>README.md</PackageReadmeFile>
    





	<PackageProjectUrl>https://github.com/Cwrstata/cw-Serial-Monitor</PackageProjectUrl>
    





	<Copyright>https://github.com/Cwrstata/cw-Serial-Monitor</Copyright>
    





	<AssemblyName>cwSerialMonitor</AssemblyName>
    





	<RootNamespace>cwSerialMonitor</RootNamespace>
    
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Serial.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SerialPortStream" Version="2.4.2" />
    <PackageReference Include="System.Management" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="src\interface\cwSerCom.Serial.cs">
      <SubType>Form</SubType>
      <DependentUpon>cwSerCom.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="icons\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
