<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <UseWPF>False</UseWPF>
    <ApplicationIcon>Serial.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Serial.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="10.0.7" />
    <PackageReference Include="System.Management" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="src\interface\cwSerCom - Copia.DataGrids.cs">
      <SubType>Form</SubType>
      <DependentUpon>cwSerCom.cs</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>